### ISSUE TITLE
Environment setup error in Anaconda for WIN11 

### ISSUE THREAD

**Issue by norton-chris** [kleelab-bch/MARS-Net#1]
Hi,
I'm having some trouble installing the environment from the environment.yml file

Here's what I ran and the output:
```
(base) C:\Users\chris\OneDrive\Documents\Han Project\MARS-Net>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libgcc-ng==9.1.0=hdf63c60_0
  - readline==8.1=h27cfd23_0
  - ca-certificates==2021.1.19=h06a4308_1
  - sqlite==3.35.4=hdfb4753_0
  - zlib==1.2.11=h7b6447c_3
  - libffi==3.3=he6710b0_2
  - setuptools==52.0.0=py36h06a4308_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - pip==21.0.1=py36h06a4308_0
  - tk==8.6.10=hbc83047_0
  - certifi==2020.12.5=py36h06a4308_0
  - xz==5.2.5=h7b6447c_0
  - ncurses==6.2=he6710b0_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - python==3.6.13=hdb3f193_0
  - openssl==1.1.1k=h27cfd23_0
```

I'm on Windows 11 and conda version 4.8.3.

Any help would be appreciated. Thanks!

**Comment by JunbongJang** [comment]
Hi Chris,

We also noticed a similar _ResolvePackageNotFound_ message from Anaconda in Windows 10.
For now, we recommend running the MARS-Net pipeline in Ubuntu 16.04 or 18.04. 
Or you can also try creating a custom Anaconda environment in Windows 11 and install the packages one by one until the code runs successfully.

**Comment by JunbongJang** [comment]
We recently added support for Windows 10!

**Comment by norton-chris** [comment]
This works on Windows 11 as well!
