### ISSUE TITLE
No module named 'cv2_rolling_ball'

### ISSUE THREAD

**Issue by norton-chris** [kleelab-bch/MARS-Net#4]
Hi,

When I run segment_edge.py I get this error: 

> Traceback (most recent call last):
>   File "C:\Users\chris\AppData\Local\Continuum\anaconda3\envs\marsnet\lib\code.py", line 91, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
>   File "C:\Program Files\JetBrains\PyCharm 2021.3.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
>     pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm 2021.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "C:/Users/chris/OneDrive/Documents/Han Project/MARS-Net/label_tool/segment_edge.py", line 22, in <module>
>     from cv2_rolling_ball import subtract_background_rolling_ball
>   File "C:\Program Files\JetBrains\PyCharm 2021.3.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
>     module = self._system_import(name, *args, **kwargs)
> ModuleNotFoundError: No module named 'cv2_rolling_ball'

 I created and activated the anaconda environment, so all the libraries should be loaded up. 

I running this code on PyCharm with the Anaconda environment, on Windows 11.

**Comment by JunbongJang** [comment]
Hi, I just updated segment_edge.py by removing the import statement that requires the 'cv2_rolling_ball' module.
We don't use that feature so it is not necessary.
